server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2_test
    username: root
    password: root
#    driver-class-name: org.h2.Driver

  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: create-drop

rsa:
  public-key: classpath:/keys/key.pub
  private-key: classpath:/keys/key.priv

  # jdbc:h2:file:/data/demo